### PR TITLE
add active text color support

### PR DESCRIPTION
**Pull request by vonovak**
# Overview
motivation: I previously used the following code 

```js
<SegmentedControlIOS
  tintColor="white"
  values={['hello', 'world']}
  style={{ backgroundColor: colors.AZURE }}
  selectedIndex={this.state.index}
  onChange={...}
/>
```
which results into the following appearance in iOS 12
Screenshot 2020-03-09 at 20 37 43

and the following appearance in iOS 13

Screenshot 2020-03-09 at 20 43 29

afaik there is no way to make the iOS 13 appearance match the one of iOS 12. In master, the color for `UIControlStateSelected` is always hard-set to white:

https://github.com/react-native-community/segmented-control/blob/9d7328ac326372849a3da37275d172ce58b71617/ios/RNCSegmentedControl.m#L70

this PR add support for setting the color for `UIControlStateSelected` separately. Now that I'm looking at it, I'd probably prefer to have one prop: `textColor: ?{ normal?: ?ColorValue, selected?: ?ColorValue}`. That would be breaking though. WDYT?

I also fixed a flow issue which prevented flow errors to be reported.

# Test Plan

I tested this locally. When we agree how to do this, I'll add this to the example app. Thanks.

### CODE REVIEW

**Comment by Naturalclar** [comment]
@vonovak Thanks for catching this!
I was looking at other libraries such as react-navigation's tab view and react-native-tabview, and they seem to have a separate props for active and inactive colors.
I feel that it should be kept as a separate props to provide similar user experience with other libraries.

If you're okay with this, I'll merge the PR and publish the package :+1:

**Comment by vonovak** [comment]
@Naturalclar ok, sounds good, let's keep it separate.

> they seem to have a separate props for active and inactive colors.

that brings up the question fo how to name this prop: should it be `selectedTextColor` or `activeTextColor` (or even something else) - which do you like better?

**Comment by Naturalclar** [comment]
@vonovak I prefer `activeTextColor`, since it makes it to use the term `inactive` if I need it, which sounds more natural than `unselected` ..or `deselected`?
If you don't mind, could you make that change? Thanks so much :+1:

**Comment by vonovak** [comment]
@Naturalclar I renamed it to `activeTextColor` as I also like it better. I added the prop to readme. Thanks. 👍

**Comment by Naturalclar** [comment]
@vonovak Thanks! published `1.2.0` :tada:
(also, I should have approved the PR before merging.. I've set the repo config so that merging without approval won't happen in the future 😓)

**Pull request merged**
